# config/glados.yaml
glados:
  accounts:
    - username: "user1@example.com"
    - username: "user2@example.com"
  
  renewals:
    - username: "user1@example.com"
      plan_type: "plan500"
      days_threshold: 2