email:
  imap_server: "imap.qq.com"
  imap_port: 993
  username: test@qq.com
  password: test
  ssl: true
  smtp_server: "smtp.qq.com"
  smtp_port: 465
  timeout: 30
  search_folders:
    - INBOX
  notify_address: test@qq.com

glados:
  auth_url: https://glados.rocks/api/authorization
  checkin_url: https://glados.rocks/api/user/checkin
  login_api: https://glados.rocks/api/login
  login_url: https://glados.rocks/login
  status_url: https://glados.rocks/api/user/status
  redeem_url: https://glados.rocks/api/user/code

accounts:
  - name: acc@163.com
    username: acc@163.com
    balance: 0.0
    leftDays: 0
    expireAt: '2025-11-20 14:15:10'
    traffic: 0
    total_traffic: 5368709120
    cookies:
      koa:sess:
      koa:sess.sig: